### ISSUE TITLE
[BUG] PATH is polluted when running `npm run <script>`

### ISSUE THREAD

**Issue by ReenigneArcher** [npm/cli#8111]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [x] I am using the latest npm

### Current Behavior

This is the same as https://github.com/npm/npm/issues/12318, which was fixed, and then unfixed in npm v7.

https://github.com/npm/cli/issues/2808

I am trying to run an npm script from an activated python venv; but I cannot use my python venv in the script because npm overrides the path, thus making the system python interpreter the one that is picked up by the script instead of the venv python.

### Expected Behavior

Do not change path order

### Steps To Reproduce

1. Create and activate python venv: https://docs.python.org/3/library/venv.html
2. Inside of activated venv, run `python -m pip install requests`
3. Inside the activated venv, run `python3 -c "import requests"`
4. Then, with this config...
```json
{
    "name": "python-venv-bug",
    "version": "0.1.0",
    "description": "Python venv bug",
    "scripts": {
        "python-venv": "python3 -c \"import requests\""
    }
}
```

5. Run `npm run python-venv` (also from the activated venv)
6. See the output when running the npm version fails.

### Environment

- npm: 11.1.0
- Node.js: v22.12.0
- OS Name: Windows 11
- System Model Name:
- npm config:
```ini
; "builtin" config from C:\Users\ReenigneArcher\AppData\Roaming\npm\node_modules\npm\npmrc

prefix = "C:\\Users\\ReenigneArcher\\AppData\\Roaming\\npm"

; node bin location = C:\Program Files\nodejs\node.exe
; node version = v22.12.0
; npm local prefix = C:\Users\ReenigneArcher\Dev\git\devicon
; npm version = 11.1.0
; cwd = C:\Users\ReenigneArcher\Dev\git\devicon
; HOME = C:\Users\ReenigneArcher
; Run `npm config ls -l` to show all defaults.
```

**Comment by kchindam-infy** [comment]
The provided package.json in the reproduce step is wrong(not valid json),
correct is:
{
    "name": "python-venv-bug",
    "version": "0.1.0",
    "description": "Python venv bug",
    "scripts": {
        "python-venv": "python3 -c \"import sys; print(sys.executable)\""
    }
}
when i fixed the package.json it worked fine and expected behaviour is satisfied

**Comment by ReenigneArcher** [comment]
The issue still exists if you remove the trailing commas (I just missed that when reducing to a simplified version).

It does use not use the correct python executable, from the virtual environment.

**Comment by ReenigneArcher** [comment]
Here's a real world example: https://github.com/devicons/devicon/pull/2360

This will use the system installed python, instead of the one from the active virtual environment.

Why it's a problem? The script cannot find dependencies installed to the venv, AND the python executable set as the default on the system PATH, may not be the same version that's setup in the venv.

I updated the original post to have a more clear example that it does not work.

Edit: I just tested on a second machine, and it does seem to work. I will test on the original computer and report back.

**Comment by ReenigneArcher** [comment]
The problem was I was using `python3` in the script, but everything works when I use `python`.
