### ISSUE TITLE
[BC BREAK] version 11.6.2 breaks CI

### ISSUE THREAD

**Issue by ro0NL** [npm/cli#8669]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This issue exists in the latest npm version

- [x] I am using the latest npm

### Current Behavior

Hi,

We notice our CI starts failing for the following _patch_ update:

| Package | Update | Change |
|---|---|---|
| [npm](https://redirect.github.com/npm/cli) | patch | `11.6.0` -> `11.6.2` |

Producing:

```
 > [build 7/9] RUN --mount=type=cache,target=/root/.npm     npm clean-install --legacy-peer-deps --logs-max=0:
2.769 npm error [--include <prod|dev|optional|peer> [--include <prod|dev|optional|peer> ...]]
2.769 npm error [--strict-peer-deps] [--foreground-scripts] [--ignore-scripts] [--no-audit]
2.769 npm error [--no-bin-links] [--no-fund] [--dry-run]
2.769 npm error [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
2.769 npm error [--workspaces] [--include-workspace-root] [--install-links]
2.769 npm error
2.769 npm error aliases: clean-install, ic, install-clean, isntall-clean
2.769 npm error
2.769 npm error Run "npm help ci" for more info
2.770 npm error Log files were not written due to the config logs-max=0
```

If i manually fiddle with it in a container, i see debug log:

```
 `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
```

But im not sure why our package.json and package-lock.json wouldnt be in sync ...

We always kept our package-lock.json in sync using `npm clean-install --legacy-peer-deps && npm install --legacy-peer-deps --package-lock-only`

Is there a related change in this _patch_ release?

### Environment

- npm: 11.6.2
- Node.js: 22.19
- OS Name: Ubunutu
- System Model Name: Gitub Actions
- npm config:
```ini
; "user" config from /root/.npmrc

engine-strict = true

; node bin location = /usr/local/bin/node
; node version = v22.19.0
; npm local prefix = /app
; npm version = 11.6.2
; cwd = /app
; HOME = /root
; Run `npm config ls -l` to show all defaults.
```

**Comment by ro0NL** [comment]
i can confirm `11.6.1` still works correctly:

```
#11 23.88 added 1441 packages, and audited 1442 packages in 24s
#11 23.88 
#11 23.88 48 packages are looking for funding
#11 23.88   run `npm fund` for details
#11 23.95 
...
#11 23.95 
#11 23.95 To address issues that do not require attention, run:
#11 23.95   npm audit fix
#11 23.95 
#11 23.95 To address all issues possible (including breaking changes), run:
#11 23.95   npm audit fix --force
#11 23.95 
#11 23.95 Some issues need review, and may require choosing
#11 23.95 a different dependency.
#11 23.95 
#11 23.95 Run `npm audit` for details.
#11 23.95 npm notice
#11 23.95 npm notice New patch version of npm available! 11.6.1 -> 11.6.2
#11 23.95 npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.6.2
#11 23.95 npm notice To update run: npm install -g npm@11.6.2
#11 23.95 npm notice
```

**Comment by ebachle** [comment]
We're also seeing this, potentially specifically around optionalDependencies:

```
#14 [build-base  3/16] RUN npm ci --omit=dev &&     cp -r node_modules /tmp/prod_node_modules  &&     npm ci
#14 5.540 npm warn EBADENGINE Unsupported engine {
#14 5.540 npm warn EBADENGINE   package: 'warehouse-service@1.0.0',
#14 5.540 npm warn EBADENGINE   required: { node: '^22.14.0', npm: '^10.2' },
#14 5.540 npm warn EBADENGINE   current: { node: 'v22.16.0', npm: '11.6.2' }
#14 5.540 npm warn EBADENGINE }
#14 5.563 npm error code EUSAGE
#14 5.568 npm error
#14 5.568 npm error `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
#14 5.568 npm error
#14 5.568 npm error Missing: @parcel/watcher-android-arm64@2.5.1 from lock file
#14 5.568 npm error Missing: @parcel/watcher-darwin-x64@2.5.1 from lock file
#14 5.568 npm error Missing: @parcel/watcher-freebsd-x64@2.5.1 from lock file
#14 5.568 npm error Missing: @parcel/watcher-linux-arm-glibc@2.5.1 from lock file
#14 5.568 npm error Missing: @parcel/watcher-linux-arm-musl@2.5.1 from lock file
#14 5.568 npm error Missing: @parcel/watcher-linux-arm64-glibc@2.5.1 from lock file
#14 5.568 npm error Missing: @parcel/watcher-linux-arm64-musl@2.5.1 from lock file
#14 5.568 npm error Missing: @parcel/watcher-linux-x64-glibc@2.5.1 from lock file
#14 5.568 npm error Missing: @parcel/watcher-linux-x64-musl@2.5.1 from lock file
#14 5.568 npm error Missing: @parcel/watcher-win32-arm64@2.5.1 from lock file
#14 5.568 npm error Missing: @parcel/watcher-win32-ia32@2.5.1 from lock file
#14 5.568 npm error Missing: @parcel/watcher-win32-x64@2.5.1 from lock file
#14 5.568 npm error Missing: @swc/core-darwin-x64@1.5.29 from lock file
#14 5.568 npm error Missing: @swc/core-linux-arm-gnueabihf@1.5.29 from lock file
#14 5.568 npm error Missing: @swc/core-linux-arm64-gnu@1.5.29 from lock file
#14 5.568 npm error Missing: @swc/core-linux-arm64-musl@1.5.29 from lock file
#14 5.568 npm error Missing: @swc/core-linux-x64-gnu@1.5.29 from lock file
#14 5.568 npm error Missing: @swc/core-linux-x64-musl@1.5.29 from lock file
#14 5.568 npm error Missing: @swc/core-win32-arm64-msvc@1.5.29 from lock file
#14 5.568 npm error Missing: @swc/core-win32-ia32-msvc@1.5.29 from lock file
#14 5.568 npm error Missing: @swc/core-win32-x64-msvc@1.5.29 from lock file
#14 5.568 npm error Missing: @nx/nx-darwin-x64@20.8.2 from lock file
#14 5.568 npm error Missing: @nx/nx-freebsd-x64@20.8.2 from lock file
#14 5.568 npm error Missing: @nx/nx-linux-arm-gnueabihf@20.8.2 from lock file
#14 5.568 npm error Missing: @nx/nx-linux-arm64-gnu@20.8.2 from lock file
#14 5.568 npm error Missing: @nx/nx-linux-arm64-musl@20.8.2 from lock file
#14 5.568 npm error Missing: @nx/nx-linux-x64-gnu@20.8.2 from lock file
#14 5.568 npm error Missing: @nx/nx-linux-x64-musl@20.8.2 from lock file
#14 5.568 npm error Missing: @nx/nx-win32-arm64-msvc@20.8.2 from lock file
#14 5.568 npm error Missing: @nx/nx-win32-x64-msvc@20.8.2 from lock file
#14 5.568 npm error Missing: @nx/nx-darwin-x64@20.4.0 from lock file
#14 5.568 npm error Missing: @nx/nx-freebsd-x64@20.4.0 from lock file
#14 5.568 npm error Missing: @nx/nx-linux-arm-gnueabihf@20.4.0 from lock file
#14 5.568 npm error Missing: @nx/nx-linux-arm64-gnu@20.4.0 from lock file
#14 5.568 npm error Missing: @nx/nx-linux-arm64-musl@20.4.0 from lock file
#14 5.568 npm error Missing: @nx/nx-linux-x64-gnu@20.4.0 from lock file
#14 5.568 npm error Missing: @nx/nx-linux-x64-musl@20.4.0 from lock file
#14 5.568 npm error Missing: @nx/nx-win32-arm64-msvc@20.4.0 from lock file
#14 5.568 npm error Missing: @nx/nx-win32-x64-msvc@20.4.0 from lock file
#14 5.568 npm error
#14 5.568 npm error Clean install a project
#14 5.568 npm error
#14 5.568 npm error Usage:
#14 5.568 npm error npm ci
#14 5.568 npm error
#14 5.568 npm error Options:
#14 5.568 npm error [--install-strategy <hoisted|nested|shallow|linked>] [--legacy-bundling]
#14 5.568 npm error [--global-style] [--omit <dev|optional|peer> [--omit <dev|optional|peer> ...]]
#14 5.568 npm error [--include <prod|dev|optional|peer> [--include <prod|dev|optional|peer> ...]]
#14 5.568 npm error [--strict-peer-deps] [--foreground-scripts] [--ignore-scripts] [--no-audit]
#14 5.568 npm error [--no-bin-links] [--no-fund] [--dry-run]
#14 5.568 npm error [-w|--workspace <workspace-name> [-w|--workspace <workspace-name> ...]]
#14 5.568 npm error [--workspaces] [--include-workspace-root] [--install-links]
#14 5.568 npm error
#14 5.568 npm error aliases: clean-install, ic, install-clean, isntall-clean
```

This is coming from entries in the package-lock.json that look something like this:
```
        "node_modules/@parcel/watcher": {
            "version": "2.5.1",
            "resolved": "https://registry.npmjs.org/@parcel/watcher/-/watcher-2.5.1.tgz",
            "integrity": "sha512-dfUnCxiN9H4ap84DvD2ubjw+3vUNpstxa0TneY/Paat8a3R4uQZDLSvWjmznAY/DoahqTHl9V46HF/Zs3F29pg==",
            "dev": true,
            "hasInstallScript": true,
            "optional": true,
            "dependencies": {
                "detect-libc": "^1.0.3",
                "is-glob": "^4.0.3",
                "micromatch": "^4.0.5",
                "node-addon-api": "^7.0.0"
            },
            "engines": {
                "node": ">= 10.0.0"
            },
            "funding": {
                "type": "opencollective",
                "url": "https://opencollective.com/parcel"
            },
            "optionalDependencies": {
                "@parcel/watcher-android-arm64": "2.5.1",
                "@parcel/watcher-darwin-arm64": "2.5.1",
                "@parcel/watcher-darwin-x64": "2.5.1",
                "@parcel/watcher-freebsd-x64": "2.5.1",
                "@parcel/watcher-linux-arm-glibc": "2.5.1",
                "@parcel/watcher-linux-arm-musl": "2.5.1",
                "@parcel/watcher-linux-arm64-glibc": "2.5.1",
                "@parcel/watcher-linux-arm64-musl": "2.5.1",
                "@parcel/watcher-linux-x64-glibc": "2.5.1",
                "@parcel/watcher-linux-x64-musl": "2.5.1",
                "@parcel/watcher-win32-arm64": "2.5.1",
                "@parcel/watcher-win32-ia32": "2.5.1",
                "@parcel/watcher-win32-x64": "2.5.1"
            }
        },
```

Our experience is also that rollback to `npm@11.6.1` fixes this.

**Comment by Tezra** [comment]
This issue may be related to [this](https://github.com/npm/cli/issues/6787) issue. A possible work around is to run npm install twice in a row. (once to install/update, and once to fix minor lock discrepancies)

**Comment by ro0NL** [comment]
@Tezra 

> We always kept our package-lock.json in sync using `npm clean-install --legacy-peer-deps && npm install --legacy-peer-deps --package-lock-only`

im not really sure what the issue is at this point, or why we'd suddenly have "minor lock discrepancies"

**Comment by DaSchTour** [comment]
I have experience the same with 11.6.1
My renovate MRs are broken since mid September and I blamed it on renovate not working properly.

**Comment by romg974** [comment]
Same issue with `npm ci` and 11.6.2. Our solution was to revert to 11.6.1 until this is fixed. I have the feeling this is linked to #8593

**Comment by BarneyPowell** [comment]
FWIW We're seeing the same thing, in addition to other issues with 11.6.2, such as jest throwing an `Unable to find jest-util` error which I fixed by rolling back to 11.6.1. Unsure if they are related - I'll try and create a repo to reproduce the issue.

Our issue emerged due to an upstream docker image automatically installing latest npm, which we've now fixed @ 11.6.1.

**Comment by ro0NL** [comment]
I'll assume this is on someone's radar at npm.

**Comment by ebachle** [comment]
@ro0NL did this get fixed and that's why you're closing it?  Or because it doesn't have responses?  We're still pinned to an old version and I'd be happy to take over keeping track of this issue if it's still a problem.

**Comment by ro0NL** [comment]
@ebachle it's not resolved; i assume this is issue is tracked by now, with someone at npm / a repo member

**Comment by mstandley-tempus** [comment]
i wouldn't assume that -- can you reopen it and leave it open until we get confirmation that the npm team is on the case?

**Comment by ebachle** [comment]
@ro0NL yeah, my understanding is that they tend to track these kind of issues from the open github issues, so reopening it would be helpful

**Comment by ro0NL** [comment]
let's just say there are 250+ open issues that needs triage, i dont want to enforce this as a priority

**Comment by mstandley-tempus** [comment]
> let's just say there are 250+ open issues that needs triage, i dont want to enforce this as a priority

it's better to leave it open so the npm devs can make the determination about priority.  closing it means they won't see it, so they'll have to wait until someone else reports this again to find out they have a regression in 11.6.2. 

so IMO you wouldn't be doing them any favors leaving it closed, it's the opposite: reporting this bug in the first place was a valuable contribution from you, not something to be swept under the rug

**Comment by DaSchTour** [comment]
When I first saw the issue closed I though its finally resolved. That was a big disappointment seeing that it was just closed without being resolved.

**Comment by DaSchTour** [comment]
Hopefully it will also be fixed with this PR https://github.com/npm/cli/pull/8645

**Comment by arkon** [comment]
I got bit by this today with the `node:24-alpine` Docker image being updated. 

Can we reopen this so it can actually get triaged?

**Comment by slifty** [comment]
This may be closed (I agree it shouldn't have been!), but this one is open: https://github.com/npm/cli/issues/8726

**Comment by dominykas** [comment]
Still a problem in 11.6.3

**Comment by TheRealWaldo** [comment]
@ro0NL please re-open this; there are many of us suffering from the problem and the only way for the maintainers to have this on their radar is if the issue is open.

None of us can re-open it for you.

**Comment by ebachle** [comment]
@TheRealWaldo just shift over to https://github.com/npm/cli/issues/8726

It's a way better report and clearly OP isn't going to reopen
